#line 2 "lexer.cpp"

#line 4 "lexer.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 0
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
#if defined(__GNUC__) && __GNUC__ >= 3
__attribute__((__noreturn__))
#endif
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 129
#define YY_END_OF_BUFFER 130
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[450] =
    {   0,
        0,    0,    0,    0,  130,  128,  126,  125,  110,  111,
      111,  111,  124,  120,  116,  118,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,  128,  128,  128,  128,  128,  128,  108,
      109,  111,  128,  122,  113,  124,    0,  124,  121,  123,
      115,  119,    0,    0,    0,    0,   10,    0,    0,   35,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,  100,
       37,   43,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   18,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,  114,    0,  117,    1,
        6,    0,    8,    9,    0,   11,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  112,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   76,    0,   32,    0,    0,    0,    0,    0,
        0,   87,   23,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   93,    0,    0,   54,    0,    0,
        0,    0,    0,    0,    0,    0,    0,   53,    0,    0,

        0,   92,    0,    0,    0,    0,    0,    7,    0,    0,
        0,    0,    0,   13,   72,   83,    0,    0,    0,    0,
        0,    0,   96,   84,    0,    0,    0,   26,    0,    0,
       28,   29,    0,    0,    0,    0,    0,    0,    0,    0,
       33,   64,    0,    0,    0,    0,    0,    0,   41,   39,
       45,   46,    0,   95,    0,    0,   44,   48,    0,    0,
        0,    0,    0,  127,    0,    0,    0,    0,    0,   65,
       90,   68,    0,   69,    0,    0,    0,    0,    0,    0,
      106,    0,    0,    0,    0,    0,    0,   20,    0,  102,
        3,   86,    0,    0,    0,   14,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  107,    0,   78,    0,    0,   34,    0,
       17,   38,    0,    0,   47,  103,    0,   49,   50,    0,
        0,    0,    0,    0,   52,  105,    0,    0,    0,    0,
        0,    5,    0,    0,    0,   56,    0,    0,    0,    0,
       59,    0,   77,    0,    0,    4,    0,    0,   15,    0,
        0,    0,   25,    0,    0,    0,   79,   30,    0,    0,
        0,   94,    0,    0,   36,   97,   40,    0,    0,    0,
        0,  104,    0,   42,    0,   98,   81,   88,   91,    0,
        0,    0,    0,   22,   57,   58,    0,   12,    0,   71,

      101,    0,    0,   80,   24,    0,    0,    0,   73,    0,
        0,   31,    0,   60,   51,    0,   67,   19,    0,    0,
       74,    0,    0,   82,    0,    0,   16,   99,   27,    0,
       62,   61,    0,    0,   75,    0,   55,    0,   66,    0,
        0,   63,   21,   85,   89,    2,    0,   70,    0
    } ;

static yyconst YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    1,    1,    1,    5,    6,    1,    5,
        5,    5,    5,    5,    5,    7,    5,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    1,    5,    9,
       10,   11,    1,    1,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,    1,
       37,    1,   38,    5,    1,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,    1,    1,   64,    1,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst YY_CHAR yy_meta[65] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1
    } ;

static yyconst flex_uint16_t yy_base[450] =
    {   0,
        0,    0,   53,   54,  202,  902,  902,  902,  190,  902,
      157,  150,   60,   59,  140,  124,   79,   60,  125,  170,
       36,  215,   43,   61,   61,   48,   63,   69,   71,   58,
      101,   58,   56,  123,  259,  165,  115,  108,  142,  902,
      902,   63,   72,  902,  902,  111,   69,   74,   64,  902,
      902,  902,  110,  156,  159,  103,  124,  110,  138,  902,
      163,  168,  165,  205,  182,  174,  219,  201,  178,  190,
      250,  217,  229,  220,  224,  233,  241,  256,  251,  902,
      303,  902,  267,  252,  272,  270,  284,  295,  268,  277,
      290,  309,  298,  311,  312,  317,  318,  318,  305,  319,

      315,  331,  336,  323,  352,  340,  358,  340,  340,  354,
      361,  368,  362,  370,  371,  357,  902,  380,  902,  902,
      902,  374,  902,  902,  380,  902,  359,  376,  366,  390,
      369,  386,  372,  372,  383,  396,  416,  420,  410,  423,
      421,  424,  408,  902,  427,  414,  428,  414,  422,  430,
      417,  426,  438,  436,  427,  431,  424,  438,  445,  454,
      463,  464,  456,  459,  902,  455,  473,  470,  476,  480,
      481,  902,  902,  471,  459,  480,  482,  475,  486,  472,
      488,  482,  487,  486,  902,  494,  492,  902,  480,  499,
      501,  498,  505,  516,  515,  524,  507,  902,  528,  519,

      534,  902,  517,  536,  518,  525,  536,  902,  528,  522,
      543,  535,  542,  902,  902,  902,  542,  535,  544,  553,
      547,  552,  575,  902,  566,  560,  563,  568,  578,  576,
      902,  902,  569,  589,  577,  587,  589,  577,  589,  599,
      902,  902,  585,  588,  579,  587,  587,  591,  902,  902,
      902,  902,  591,  902,  600,  614,  902,  902,  608,  613,
      632,  630,  616,  902,  616,  640,  622,  638,  641,  902,
      902,  902,  633,  902,  641,  633,  646,  645,  632,  643,
      902,  651,  641,  635,  637,  654,  653,  902,  658,  902,
      902,  902,  660,  646,  656,  902,  675,  671,  673,  671,

      686,  693,  694,  684,  692,  689,  685,  691,  696,  684,
      695,  701,  692,  902,  689,  902,  702,  690,  902,  704,
      902,  902,  705,  695,  902,  902,  712,  902,  902,  701,
      716,  726,  718,  736,  902,  902,  721,  734,  741,  741,
      729,  731,  731,  738,  752,  734,  750,  752,  739,  758,
      902,  746,  902,  753,  745,  902,  744,  764,  902,  748,
      757,  751,  902,  771,  771,  781,  902,  902,  774,  788,
      794,  902,  783,  779,  902,  902,  902,  798,  778,  783,
      785,  902,  801,  902,  793,  902,  902,  902,  902,  807,
      789,  791,  787,  902,  902,  902,  795,  902,  813,  902,

      902,  807,  812,  902,  902,  813,  799,  800,  902,  819,
      813,  902,  822,  902,  902,  810,  902,  902,  817,  829,
      902,  842,  833,  902,  837,  839,  902,  902,  902,  836,
      902,  902,  853,  853,  902,  843,  902,  855,  902,  841,
      857,  902,  902,  902,  902,  902,  859,  902,  902
    } ;

static yyconst flex_int16_t yy_def[450] =
    {   0,
      449,    1,    1,    1,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,   17,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,

      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,    0
    } ;

static yyconst flex_uint16_t yy_nxt[967] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
       36,   37,   38,   39,    6,    6,   40,   41,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,    6,    6,   42,   43,   43,   47,   48,   49,   50,
       71,   78,   79,   83,  119,   58,   46,   80,   84,   59,
       47,   48,   88,   89,   85,   81,   94,   95,   86,   90,
       82,   43,   43,   53,   87,   60,  118,   71,   78,   79,

       83,   54,   58,   55,   80,   84,   59,   56,   57,   88,
       89,   85,   81,   94,   95,   86,   90,   82,   46,  113,
       53,   87,   60,  118,  120,   91,  117,  114,   54,   92,
       55,  125,   93,   52,   56,   57,   61,  126,   96,  110,
      127,  111,   97,   62,  112,   98,  113,   63,   99,   51,
       64,  120,   91,   65,  114,  128,   92,   46,  125,   93,
      115,  116,   45,   61,  126,   96,  110,  127,  111,   97,
       62,  112,   98,  123,   63,   99,  106,   64,  121,  131,
       65,   66,  128,  132,  107,   67,  122,  115,  116,   68,
      108,  129,  130,  109,  124,   69,  133,  137,   70,   44,

      123,  449,  449,  106,  138,  121,  131,  449,   66,  145,
      132,  107,   67,  122,  449,  146,   68,  108,  129,  130,
      109,  124,   69,  133,  137,   70,   72,  134,  135,  136,
      143,  138,  139,  144,   73,  140,  145,   74,  449,  151,
       75,  141,  146,   76,  152,  153,   77,  449,  142,  449,
      449,  449,  154,   72,  134,  135,  136,  143,  155,  139,
      144,   73,  140,  156,   74,  147,  151,   75,  141,  148,
       76,  152,  153,   77,  100,  142,  149,  101,  102,  154,
      150,  157,  103,  158,  104,  155,  164,  165,  166,  105,
      156,  167,  147,  168,  449,  169,  148,  170,  173,  174,

      449,  100,  449,  149,  101,  102,  449,  150,  157,  103,
      158,  104,  175,  164,  165,  166,  105,  159,  167,  171,
      168,  172,  169,  176,  170,  173,  174,  160,  177,  161,
      178,  180,  162,  163,  181,  183,  179,  184,  185,  175,
      189,  186,  187,  182,  159,  190,  171,  191,  172,  188,
      176,  192,  195,  449,  160,  177,  161,  178,  180,  162,
      163,  181,  183,  179,  184,  185,  198,  189,  186,  187,
      182,  199,  190,  200,  191,  201,  188,  193,  192,  195,
      194,  196,  197,  202,  203,  205,  206,  207,  449,  209,
      204,  210,  211,  198,  208,  212,  213,  216,  199,  217,

      200,  218,  201,  219,  193,  214,  220,  194,  196,  197,
      202,  203,  205,  206,  207,  124,  209,  204,  210,  211,
      215,  208,  212,  213,  216,  221,  217,  222,  218,  225,
      219,  223,  214,  220,  226,  224,  227,  228,  229,  230,
      231,  232,  124,  233,  234,  235,  236,  215,  237,  238,
      241,  239,  221,  242,  222,  243,  225,  244,  223,  240,
      245,  226,  224,  227,  228,  229,  230,  231,  232,  246,
      233,  234,  235,  236,  247,  237,  238,  241,  239,  248,
      242,  249,  243,  250,  244,  251,  240,  245,  252,  253,
      254,  255,  256,  257,  258,  259,  246,  260,  261,  262,

      263,  247,  264,  265,  266,  267,  248,  268,  249,  269,
      250,  270,  251,  271,  272,  252,  253,  254,  255,  256,
      257,  258,  259,  273,  260,  261,  262,  263,  274,  264,
      265,  266,  267,  275,  268,  276,  269,  278,  270,  279,
      271,  272,  280,  281,  283,  285,  284,  277,  286,  287,
      273,  288,  282,  289,  290,  274,  291,  292,  293,  294,
      275,  295,  276,  296,  278,  297,  279,  298,  299,  280,
      281,  283,  285,  284,  277,  286,  287,  300,  288,  282,
      289,  290,  301,  291,  292,  293,  294,  302,  295,  303,
      296,  304,  297,  305,  298,  299,  306,  307,  309,  310,

      311,  312,  314,  315,  300,  313,  308,  316,  317,  301,
      318,  319,  320,  321,  302,  322,  303,  323,  304,  324,
      305,  325,  326,  306,  307,  309,  310,  311,  312,  314,
      315,  327,  313,  308,  316,  317,  328,  318,  319,  320,
      321,  329,  322,  330,  323,  331,  324,  332,  325,  326,
      333,  334,  335,  336,  337,  338,  339,  340,  327,  341,
      342,  343,  344,  328,  345,  346,  347,  348,  329,  349,
      330,  350,  331,  351,  332,  352,  353,  333,  334,  335,
      336,  337,  338,  339,  340,  354,  341,  342,  343,  344,
      355,  345,  346,  347,  348,  356,  349,  357,  350,  358,

      351,  359,  352,  353,  360,  361,  362,  363,  364,  365,
      366,  367,  354,  368,  369,  370,  371,  355,  372,  373,
      374,  375,  356,  376,  357,  377,  358,  378,  359,  379,
      380,  360,  361,  362,  363,  364,  365,  366,  367,  381,
      368,  369,  370,  371,  382,  372,  373,  374,  375,  383,
      376,  384,  377,  385,  378,  386,  379,  380,  387,  388,
      389,  390,  391,  392,  393,  394,  381,  395,  396,  397,
      398,  382,  399,  400,  401,  402,  383,  403,  384,  404,
      385,  405,  386,  406,  407,  387,  388,  389,  390,  391,
      392,  393,  394,  408,  395,  396,  397,  398,  409,  399,

      400,  401,  402,  410,  403,  411,  404,  412,  405,  413,
      406,  407,  414,  415,  416,  417,  418,  419,  420,  421,
      408,  422,  423,  424,  425,  409,  426,  427,  428,  429,
      410,  430,  411,  431,  412,  432,  413,  433,  434,  414,
      415,  416,  417,  418,  419,  420,  421,  435,  422,  423,
      424,  425,  436,  426,  427,  428,  429,  437,  430,  438,
      431,  439,  432,  440,  433,  434,  441,  442,  443,  444,
      445,  446,  447,  448,  435,  449,  449,  449,  449,  436,
      449,  449,  449,  449,  437,  449,  438,  449,  439,  449,
      440,  449,  449,  441,  442,  443,  444,  445,  446,  447,

      448,    5,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449
    } ;

static yyconst flex_int16_t yy_chk[967] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,   13,   13,   14,   14,
       21,   23,   24,   26,   49,   18,   47,   25,   27,   18,
       48,   48,   29,   30,   28,   25,   32,   33,   28,   30,
       25,    3,    4,   17,   28,   18,   43,   21,   23,   24,

       26,   17,   18,   17,   25,   27,   18,   17,   17,   29,
       30,   28,   25,   32,   33,   28,   30,   25,   46,   38,
       17,   28,   18,   43,   53,   31,   42,   38,   17,   31,
       17,   56,   31,   16,   17,   17,   19,   57,   34,   37,
       58,   37,   34,   19,   37,   34,   38,   19,   34,   15,
       19,   53,   31,   19,   38,   59,   31,   12,   56,   31,
       39,   39,   11,   19,   57,   34,   37,   58,   37,   34,
       19,   37,   34,   55,   19,   34,   36,   19,   54,   62,
       19,   20,   59,   62,   36,   20,   54,   39,   39,   20,
       36,   61,   61,   36,   55,   20,   63,   65,   20,    9,

       55,    5,    0,   36,   66,   54,   62,    0,   20,   69,
       62,   36,   20,   54,    0,   70,   20,   36,   61,   61,
       36,   55,   20,   63,   65,   20,   22,   64,   64,   64,
       68,   66,   67,   68,   22,   67,   69,   22,    0,   72,
       22,   67,   70,   22,   73,   74,   22,    0,   67,    0,
        0,    0,   75,   22,   64,   64,   64,   68,   76,   67,
       68,   22,   67,   77,   22,   71,   72,   22,   67,   71,
       22,   73,   74,   22,   35,   67,   71,   35,   35,   75,
       71,   78,   35,   79,   35,   76,   83,   84,   85,   35,
       77,   86,   71,   86,    0,   87,   71,   87,   89,   90,

        0,   35,    0,   71,   35,   35,    0,   71,   78,   35,
       79,   35,   91,   83,   84,   85,   35,   81,   86,   88,
       86,   88,   87,   92,   87,   89,   90,   81,   93,   81,
       94,   95,   81,   81,   96,   97,   94,   98,   99,   91,
      101,  100,  100,   96,   81,  102,   88,  103,   88,  100,
       92,  104,  106,    0,   81,   93,   81,   94,   95,   81,
       81,   96,   97,   94,   98,   99,  108,  101,  100,  100,
       96,  109,  102,  110,  103,  111,  100,  105,  104,  106,
      105,  107,  107,  112,  113,  114,  115,  116,    0,  122,
      113,  125,  127,  108,  118,  128,  129,  131,  109,  132,

      110,  133,  111,  134,  105,  130,  135,  105,  107,  107,
      112,  113,  114,  115,  116,  118,  122,  113,  125,  127,
      130,  118,  128,  129,  131,  136,  132,  137,  133,  139,
      134,  138,  130,  135,  140,  138,  141,  142,  143,  145,
      146,  147,  118,  148,  149,  150,  151,  130,  152,  153,
      155,  154,  136,  156,  137,  157,  139,  158,  138,  154,
      159,  140,  138,  141,  142,  143,  145,  146,  147,  160,
      148,  149,  150,  151,  161,  152,  153,  155,  154,  162,
      156,  163,  157,  164,  158,  166,  154,  159,  167,  168,
      169,  170,  171,  174,  175,  176,  160,  177,  178,  179,

      179,  161,  180,  181,  182,  183,  162,  184,  163,  186,
      164,  187,  166,  189,  190,  167,  168,  169,  170,  171,
      174,  175,  176,  191,  177,  178,  179,  179,  192,  180,
      181,  182,  183,  193,  184,  194,  186,  195,  187,  196,
      189,  190,  197,  199,  200,  201,  200,  194,  203,  204,
      191,  205,  199,  206,  207,  192,  209,  210,  211,  212,
      193,  213,  194,  217,  195,  218,  196,  219,  220,  197,
      199,  200,  201,  200,  194,  203,  204,  221,  205,  199,
      206,  207,  222,  209,  210,  211,  212,  223,  213,  225,
      217,  226,  218,  227,  219,  220,  228,  229,  230,  233,

      234,  235,  236,  237,  221,  235,  229,  238,  239,  222,
      240,  243,  244,  245,  223,  246,  225,  247,  226,  248,
      227,  253,  255,  228,  229,  230,  233,  234,  235,  236,
      237,  256,  235,  229,  238,  239,  259,  240,  243,  244,
      245,  260,  246,  261,  247,  262,  248,  263,  253,  255,
      265,  266,  267,  268,  269,  273,  275,  276,  256,  277,
      278,  279,  280,  259,  282,  283,  284,  285,  260,  286,
      261,  287,  262,  289,  263,  293,  294,  265,  266,  267,
      268,  269,  273,  275,  276,  295,  277,  278,  279,  280,
      297,  282,  283,  284,  285,  298,  286,  299,  287,  300,

      289,  301,  293,  294,  302,  303,  304,  305,  306,  307,
      308,  309,  295,  310,  311,  312,  313,  297,  315,  317,
      318,  320,  298,  323,  299,  324,  300,  327,  301,  330,
      331,  302,  303,  304,  305,  306,  307,  308,  309,  332,
      310,  311,  312,  313,  333,  315,  317,  318,  320,  334,
      323,  337,  324,  338,  327,  339,  330,  331,  340,  341,
      342,  343,  344,  345,  346,  347,  332,  348,  349,  350,
      352,  333,  354,  355,  357,  358,  334,  360,  337,  361,
      338,  362,  339,  364,  365,  340,  341,  342,  343,  344,
      345,  346,  347,  366,  348,  349,  350,  352,  369,  354,

      355,  357,  358,  370,  360,  371,  361,  373,  362,  374,
      364,  365,  378,  379,  380,  381,  383,  385,  390,  391,
      366,  392,  393,  397,  399,  369,  402,  403,  406,  407,
      370,  408,  371,  410,  373,  411,  374,  413,  416,  378,
      379,  380,  381,  383,  385,  390,  391,  419,  392,  393,
      397,  399,  420,  402,  403,  406,  407,  422,  408,  423,
      410,  425,  411,  426,  413,  416,  430,  433,  434,  436,
      438,  440,  441,  447,  419,    0,    0,    0,    0,  420,
        0,    0,    0,    0,  422,    0,  423,    0,  425,    0,
      426,    0,    0,  430,  433,  434,  436,  438,  440,  441,

      447,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  449
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 4 "lexer.l"
	#pragma warning (disable: 4005)

	#include <iostream>
	#include <cmath>
	#include <string>
	using namespace std;

	extern void yyerror(const char*);

	#include "parser.h"

#line 839 "lexer.cpp"

#define INITIAL 0
#define BTWMODE 1

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#if defined(_MSC_BUILD) && (defined(_WIN32) || defined(_WIN64) )
		#include <io.h>
		#include <process.h>
#else
		#include <unistd.h>
#endif
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * _in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * _out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput (int c,char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 19 "lexer.l"


#line 1066 "lexer.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 450 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 902 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "lexer.l"
{ return ADD; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 22 "lexer.l"
{ return CONSTRAINT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 23 "lexer.l"
{ return ALTER; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "lexer.l"
{ return COLUMN; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 25 "lexer.l"
{ return TABLE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 26 "lexer.l"
{ return ALL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 27 "lexer.l"
{ BEGIN INITIAL; return AND; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 28 "lexer.l"
{ return ANDOP; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 29 "lexer.l"
{ return ANY; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 30 "lexer.l"
{ return AS; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 31 "lexer.l"
{ return ASC; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 32 "lexer.l"
{ BEGIN BTWMODE; return BETWEEN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 33 "lexer.l"
{ return CASE; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 34 "lexer.l"
{ return CHECK; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 35 "lexer.l"
{ return CREATE; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 36 "lexer.l"
{ return DATABASE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 37 "lexer.l"
{ return INDEX; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 38 "lexer.l"
{ return OR; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 39 "lexer.l"
{ return REPLACE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 40 "lexer.l"
{ return VIEW; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 41 "lexer.l"
{ return PROCEDURE; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 42 "lexer.l"
{ return UNIQUE; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 43 "lexer.l"
{ return NOT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 44 "lexer.l"
{ return DEFAULT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 45 "lexer.l"
{ return DELETE; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 46 "lexer.l"
{ return DESC; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 47 "lexer.l"
{ return DISTINCT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 48 "lexer.l"
{ return DROP; }	
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 49 "lexer.l"
{ return EXEC; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 50 "lexer.l"
{ return EXISTS; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 51 "lexer.l"
{ return FOREIGN; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 52 "lexer.l"
{ return KEY; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 53 "lexer.l"
{ return FROM; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 54 "lexer.l"
{ return GROUP; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 55 "lexer.l"
{ return BY; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "lexer.l"
{ return HAVING; }	
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "lexer.l"
{ return IN; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "lexer.l"
{ return INNER; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "lexer.l"
{ return JOIN; }	
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "lexer.l"
{ return INSERT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "lexer.l"
{ return INTO; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 62 "lexer.l"
{ return SELECT; }	
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 63 "lexer.l"
{ return IS; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 64 "lexer.l"
{ return NILL; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 65 "lexer.l"
{ return LEFT; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 66 "lexer.l"
{ return LIKE; }	
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 67 "lexer.l"
{ return LIMIT; }	
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 68 "lexer.l"
{ return ONLY; }  
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 69 "lexer.l"
{ return ORDER; }	
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 70 "lexer.l"
{ return OUTER; }	
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 71 "lexer.l"
{ return PRIMARY; }	
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 72 "lexer.l"
{ return RIGHT; }	
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 73 "lexer.l"
{ return TOP; }	
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 74 "lexer.l"
{ return SET; }	
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 75 "lexer.l"
{ return TRUNCATE; }	
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 76 "lexer.l"
{ return UNION; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 77 "lexer.l"
{ return UPDATE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 78 "lexer.l"
{ return VALUES; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 79 "lexer.l"
{ return WHERE; }
	YY_BREAK
/* Hql function */
case 60:
YY_RULE_SETUP
#line 82 "lexer.l"
{ return MANAGED;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 83 "lexer.l"
{ return EXTERNAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 84 "lexer.l"
{ return EXTENDED;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 85 "lexer.l"
{ return FORMATTED;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 86 "lexer.l"
{ return FULL;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 87 "lexer.l"
{ return SEMI;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return CARTISIAN;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 89 "lexer.l"
{ return PRODUCT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 90 "lexer.l"
{ return SIDE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 91 "lexer.l"
{ return SORT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 92 "lexer.l"
{ return DISTRIBUTED;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return CLUSTER;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 94 "lexer.l"
{ return CAST;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return EXPLAIN;}
	YY_BREAK
/* Data Types */
case 74:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return TINYINT; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 98 "lexer.l"
{ return SMALLINT; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return INT; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return BIGINT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 101 "lexer.l"
{ return FLOAT; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 102 "lexer.l"
{ return DOUBLE; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return DECIMAL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return STRING; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 105 "lexer.l"
{ return VARCHAR; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return CHAR; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return DATE; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return TIMESTAMP; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 109 "lexer.l"
{ return ARRAY; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return MAP; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return STRUCT; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 112 "lexer.l"
{ return UNIONTYPE; }
	YY_BREAK
/* HiveQL Commands */
case 90:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return SHOW; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 116 "lexer.l"
{ return TABLES; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 117 "lexer.l"
{ return USE; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 118 "lexer.l"
{ return ROW; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 119 "lexer.l"
{ return FIELDS; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 120 "lexer.l"
{ return LOAD; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 121 "lexer.l"
{ return DATA; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 122 "lexer.l"
{ return INPATH; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 123 "lexer.l"
{ return STORED; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 124 "lexer.l"
{ return DESCRIBE; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 125 "lexer.l"
{ return IF; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return COMMENT; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 127 "lexer.l"
{ return WITH; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return LOCAL; }
	YY_BREAK
/* Operators */
case 104:
#line 132 "lexer.l"
case 105:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return RLIKE; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return TRUE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return FALSE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return OPENBRACKET; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return CLOSEBRACKET; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 137 "lexer.l"
{ return NOT; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 138 "lexer.l"
{ return yytext[0]; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 139 "lexer.l"
{ return DIV; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 142 "lexer.l"
{ return ANDOP; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 143 "lexer.l"
{ return OR; }
	YY_BREAK
case 115:
#line 146 "lexer.l"
case 116:
YY_RULE_SETUP
#line 146 "lexer.l"
{ yylval = 4; return COMPARISON; } /* =4 <=>12 >2 >=6 <1 <= <>*/
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 147 "lexer.l"
{ yylval = 12; return COMPARISON; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 148 "lexer.l"
{ yylval = 2; return COMPARISON; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 149 "lexer.l"
{ yylval = 6; return COMPARISON; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 150 "lexer.l"
{ yylval = 1; return COMPARISON; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 151 "lexer.l"
{ yylval = 5; return COMPARISON; }
	YY_BREAK
case 122:
#line 153 "lexer.l"
case 123:
YY_RULE_SETUP
#line 153 "lexer.l"
{ yylval = 3; return COMPARISON; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 155 "lexer.l"
{ yylval = atof(yytext); return NUM; }
	YY_BREAK
case 125:
/* rule 125 can match eol */
YY_RULE_SETUP
#line 156 "lexer.l"
{ return '\n'; }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 157 "lexer.l"
{ /* empty */ }
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 158 "lexer.l"
{ yyterminate(); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 159 "lexer.l"
{	/*error handling */		yyerror("unknown word");}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 161 "lexer.l"
ECHO;
	YY_BREAK
#line 1764 "lexer.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BTWMODE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	yy_size_t number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (yy_size_t) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 450 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 450 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 449);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		yy_size_t number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = (yy_size_t)size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

		#if defined(_MSC_BUILD) && ( defined(_WIN32) || defined(_WIN64) )
        b->yy_is_interactive = file ? (_isatty( _fileno(file) ) > 0) : 0;
		#else
		b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
		#endif
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1; // After all that talk, this was set to 1 anyways...
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
			(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 161 "lexer.l"
